allprojects {
    repositories {
        google()
        mavenCentral()
    }
    tasks.whenTaskAdded { task ->
        if (task.name.contains("AarMetadata")) {
            task.enabled = false
        }
    }
}

rootProject.buildDir = new File(rootProject.projectDir, "../build").getCanonicalFile()
subprojects {
    if (project.projectDir.canonicalPath.startsWith(rootProject.projectDir.canonicalPath)) {
        project.buildDir = new File(rootProject.buildDir, project.name)
    }
}
subprojects {
    project.evaluationDependsOn(":app")
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
